version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    volumes:
      - ./backend/:/urs/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    networks:
      - main

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - main

networks:
  main:
    driver: bridge
